# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-11 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cria_data',
            new_name='criar_data',
        ),
        migrations.AddField(
            model_name='post',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
